### ISSUE TITLE
Choose a build flavour 

### ISSUE THREAD

**Issue by JoelBrenstrum** [aloisdeniel/vsts-flutter-tasks#1]
It would be nice if we could specify a build flavour `debug`, `release`. 
the simulator also cant be built in release mode

I created this branch with the change https://github.com/JoelBrenstrum/vsts-flutter-tasks/tree/build-flavour

**Comment by aloisdeniel** [comment]
Thanks a lot for your contribution!

Just added it and published a new release on [marketplace](https://marketplace.visualstudio.com/items?itemName=aloisdeniel.flutter).
