### ISSUE TITLE
Flutter clean task - custom commands

### ISSUE THREAD

**Issue by andreujuanc** [aloisdeniel/vsts-flutter-tasks#10]
It'd be nice to have a custom argument task, or at least one per option needed.

I have a build agent and cache must be cleaned before building.  
For this it'd be cool to have a proper task instead of a shell script.

Thanks

**Comment by aloisdeniel** [comment]
The `$(FlutterToolPath)` environment variable points to the flutter folder.

You can use it for your custom commands.
