### ISSUE TITLE
Always fails and not able to locate SDK from PATH 

### ISSUE THREAD

**Issue by vinaypatel** [aloisdeniel/vsts-flutter-tasks#12]
Error: Unable to locate executable file: '<PATH>\flutter'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

I am planing to use existing SDK which is already configured on machine.

Please advice

**Comment by aloisdeniel** [comment]
Hello, did you set a FlutterToolPath environment variable that points to your flutter SDK ?

**Comment by vinaypatel** [comment]
It worked ! , Thanks :)
