### ISSUE TITLE
Didn´t find flutter SDK in linux

### ISSUE THREAD

**Issue by rgutlich** [aloisdeniel/vsts-flutter-tasks#14]
When I run the flutter install step in Azure, it didn´t find the right file (it looks for .zip instead of .tar.xz):

![image](https://user-images.githubusercontent.com/50369624/57327576-ad5ebe80-70e5-11e9-8799-fb559adabe4b.png)

![image](https://user-images.githubusercontent.com/50369624/57327543-9a4bee80-70e5-11e9-9347-5a3eb4e4ffe1.png)

Instead of creating the url by using the following line:

**https://storage.googleapis.com/flutter_infra/releases/${channel}/${arch}/flutter_${arch}_v${versionSpec}.zip**

I think it´s better to use **base_url** and **archive** from the _releases_${arch}.json_ file.

**Comment by Bowman74** [comment]
Same issue for me

**Comment by Jeanlanziloti** [comment]
The same here!

**Comment by AlienEngineer** [comment]
Any workaround?

**Comment by aloisdeniel** [comment]
Nice catch, I haven't any linux to try this out ! 

Unfortunately, I haven't much time right now so any PR would make me be happy ! :)

**Comment by d0mmi** [comment]
is this still not fixed?

**Comment by pparsonsesp** [comment]
I got this too. It needs to be .tar.gz on Linux

**Comment by aloisdeniel** [comment]
Should be fixed with latest version since download link is now read from [releases_linux.json](https://storage.googleapis.com/flutter_infra/releases/releases_linux.json).
