### ISSUE TITLE
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===     Could not find an option named "track-widget-creation".

### ISSUE THREAD

**Issue by Lolo13320** [aloisdeniel/vsts-flutter-tasks#15]
Hi,

could you please help me :) ?

When I try a flutter build for iOS on azure DevOps I receive the followinf error:
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Could not find an option named "track-widget-creation".

It works fine for Android...

**Comment by aloisdeniel** [comment]
I don't think it is cause by the extension. Do you need additional args ?
