### ISSUE TITLE
Can not sign iOS ipa

### ISSUE THREAD

**Issue by neigaard** [aloisdeniel/vsts-flutter-tasks#17]
Hello,

I was wondering what the status of this Flutter task is, I see there are are old open issues such as "IOS build - does not find provisioning profile". Does it work at all for iOS, can it build and sign a iOS IPA?

If so, how is this done? I have these tasks confireg in this order:

1. Install an Apple certificate
2. Install an Apple provisioning profile
3. Flutter install
4. Flutter Build (IPA)

In my Flutter project I have opened the XCode project and set it to manual provisioning and to use the certificate/profile that I install with the tasks above, but I get "No development certificates available to code sign app for device deployment".

I have also tried with automatic provisioning, but that seems  wrong because then it need to log in as me, and also it fails with "Code Signing Error: No profiles for 'XXX' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'XXX'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild."

Please could you look into this or give a status :)

Best regards
Søren

**Comment by aloisdeniel** [comment]
Hi thanks for the details. I haven’t much time right now, and no clue about this. I have to dig into Microsoft build task to find the origin of the issue. I hope to have more time next month ! I would greatly appreciate any PR on the subject ! :)

**Comment by mortenboye** [comment]
I'm experiencing the same issue. I've tried deselecting "Codesign application bundle" in the Flutter Build task, but with the same results. Maybe https://github.com/aloisdeniel/vsts-flutter-tasks/pull/16 is related?

**Comment by aloisdeniel** [comment]
I merged #16 and published a new version ([0.2.16](https://marketplace.visualstudio.com/items?itemName=aloisdeniel.flutter)).

This way you should be able to produce an unsigned package and sign it afterward with dedicated tasks.

**Comment by fryette** [comment]
@aloisdeniel any news?

**Comment by humanolaranja** [comment]
Is not possible to produce a signed package already? I'm following the documentation that says to run Install Apple Certificate BEFORE the build, but I have the same problem issue related here @aloisdeniel 

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/18094686/195691940-409353c4-88e1-4879-aba4-4fd98821368c.png">
