### ISSUE TITLE
Add entry point parameter (-t)

### ISSUE THREAD

**Issue by duncanhoggan** [aloisdeniel/vsts-flutter-tasks#20]
Please expose the entry point command line parameter.
This is the `-t` option to define a starting point other than lib/main.dart.

I'll make a PR when I've had a look at the extension structure.
Thanks

**Comment by duncanhoggan** [comment]
PR #22 Solves this issue. Will close when the PR is completed.

**Comment by aloisdeniel** [comment]
Just merged and published a new 0.2.20 version. I should be fine now! :)
