### ISSUE TITLE
Can't install Flutter SDK

### ISSUE THREAD

**Issue by Skyggedans** [aloisdeniel/vsts-flutter-tasks#29]
Selected stable channel and latest version for my build, and FlutterInstall is failing with the following error. 
The same behaviour is observable for other versions:

> ##[section]Starting: FlutterInstall
==============================================================================
Task         : Flutter Install
Description  : Install the Flutter environment.
Version      : 0.2.15
Author       : Aloïs Deniel
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
==============================================================================
Downloading: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.9.1+hotfix.2-stable.zip
##[error]Error: Unexpected HTTP response: 404
##[section]Finishing: FlutterInstall

**Comment by nel-sam** [comment]
@Skyggedans 

This is a duplicate of issue 14: https://github.com/aloisdeniel/vsts-flutter-tasks/issues/14

I have a PR that resolves this issue, but it's still waiting to be merged: https://github.com/aloisdeniel/vsts-flutter-tasks/pull/24

**Comment by aloisdeniel** [comment]
Choose a mac os agent for now if you can. :)
