### ISSUE TITLE
'flutter' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Ahmadre** [aloisdeniel/vsts-flutter-tasks#33]
CmdLine is not working It's crashing after "flutter doctor" command. 
I get:
```bash
   'flutter' is not recognized as an internal or external command
```

Flutter install succeeded by the way...

Can you help me?

**Comment by panzer-planet** [comment]
Hi Ahmadre,

By reading through the source I found that you can do this
`$(FlutterToolPath)/flutter doctor`

**Comment by Ahmadre** [comment]
@panzer-planet thank you soo much for the hint :) I'll try that! By the way curious github name 😂

**Comment by aloisdeniel** [comment]
Did you put the` Flutter Install` task at the beginning on your definition ?
