### ISSUE TITLE
IOS build - does not find provisioning profile

### ISSUE THREAD

**Issue by akeblom** [aloisdeniel/vsts-flutter-tasks#4]
Hi, could you point me in the right direction. It seems like I have done something wrong with my pipleline.

```
Code Signing Error: No profiles for 'com.tromb.pentaapp' were found:  Xcode couldn't find any iOS App Development provisioning profiles
````

Here is my pipeline:

![image](https://user-images.githubusercontent.com/12762329/51317039-cc621380-1a56-11e9-818a-9df035a25437.png)

**Comment by LazyDave76** [comment]
I'm seeing this too, did you figure anything out?

**Comment by akeblom** [comment]
Nope!

**Comment by danwulff** [comment]
If it's not necessary for you to use code signing (for me, I'm just trying to validate a working build not necessarily trying to create a proper package), you can utilize the `--no-codesign` flag to get a green build.

(NOTE: if you can figure out how to manually sign the final bundle after the fact, then you could end up with a valid package.)

**Comment by akeblom** [comment]
I moved to codemagic. Problem solved :)

**Comment by aloisdeniel** [comment]
Published a new version with `--no-codesign` flag ([0.2.16](https://marketplace.visualstudio.com/items?itemName=aloisdeniel.flutter)).

The resulting ipa should be signed with [App Store Task](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store).

I will publish a blog article with the fully working chain one day ! :)
