### ISSUE TITLE
Why CLI does not contain --release

### ISSUE THREAD

**Issue by ControlAdad** [aloisdeniel/vsts-flutter-tasks#40]
Hi

Why your flutter build command is :
`flutter build ios --no-codesign`
and is not
`flutter build ios --release --no-codesign`

**Comment by RemeJuan** [comment]
`--release` is an optional flag that is defaulted to true by flutter.

**Comment by Vayth** [comment]
Actually, I kind of want to ask similar question. On Android, it defaults to release
![image](https://user-images.githubusercontent.com/41632555/79403821-2636ed80-7fba-11ea-819a-557b1abb72bf.png)

However on flutter build ios, it defaults to debug
![image](https://user-images.githubusercontent.com/41632555/79403893-60a08a80-7fba-11ea-96e6-f48a2480ac5c.png)

It's from Flutter 1.12.13+hotfix.9 on Windows. I'm not sure if it's different on Mac, though.

**Comment by aloisdeniel** [comment]
Yes release mode is the default.
