### ISSUE TITLE
Flutter 1.17.0 has dropped the "v"

### ISSUE THREAD

**Issue by mcparry** [aloisdeniel/vsts-flutter-tasks#49]
The Install task contains a function "findLatestSdkVersion" and that function removes the first character from the version, expecting it to be a "v"...

return current.version.substring(1); // removing leading 'v'

It appears that, with version 1.17.0 of Flutter, they stopped putting that v into the json document at https://storage.googleapis.com/flutter_infra/releases/releases_(platform).json. The task cannot then find the flutter zip to download because it has mistakenly removed the leading "1" from the version.  I think it should be possible to override this using the "customVersion" parameter, but thought I should raise the issue anyway because builds are broken right now.

Update: this is more serious than I thought - it cannot be fixed using the "customVersion" parameter because the function "downloadAndCacheSdk" will always insert a "v" into the download URL which should not be there from v1.17.0.

**Comment by Tregan** [comment]
Yeah in findLatestSdkVersion
`return current.version.substring(1); // removing leading 'v'`
should probably be changed to 
`return current.version;`

and in downloadAndCacheSdk
`let downloadUrl = `https://storage.googleapis.com/flutter_infra/releases/${channel}/${arch}/flutter_${arch}_v${versionSpec}.zip`;`
to
`let downloadUrl = `https://storage.googleapis.com/flutter_infra/releases/${channel}/${arch}/flutter_${arch}_${versionSpec}.zip`;`

this will allow custom versioning e.g. v1.12.13+hotfix.9, but will by default not add the v

**Comment by mcparry** [comment]
@Tregan I agree.  However, anybody that already uses the "customVersion" parameter will then have to add a "v" to their parameter value.  I can't think of a better solution though.

**Comment by Tregan** [comment]
@mcparry Yep, sadly you'll have to add a 'v' in that case. But if you want to keep building on for example 1.12, where before you were using 'latest', you'll have to set a custom version anyway. I'll quickly make & test a fix and create a PR.

**Comment by OndrejKunc** [comment]
This issue is already being discussed in #46 

Until it is resolved, I stick with the old version:
```
          - task: FlutterInstall@0
            inputs:
              channel: "stable"
              version: custom
              customVersion: "1.12.13+hotfix.9"
```

**Comment by mcparry** [comment]
Oh yes, sorry, I didn't notice that #46 had already covered this problem.  I'll close this issue.

**Comment by skela** [comment]
When will this be updated in the market place? My dev ops builds still fail, even when defining custom versions.
