### ISSUE TITLE
Building APK Licenses Error

### ISSUE THREAD

**Issue by CheeseNPort** [aloisdeniel/vsts-flutter-tasks#5]
I may be missing something here. I was really pleased to find this add on so thanks :) but could do with some guidance. When building my APK I am receiving the following error.

Failed to install the following Android SDK packages as some licences have not been accepted.
build-tools;28.0.3 Android SDK Build-Tools 28.0.3
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
Using Android SDK: C:\Program Files (x86)\Android\android-sdk

I know how to do this locally, I run flutter-doctor --android-licenses but not sure how I would run this in pipelines. I thought about a script task but don't know how to accept them all without havign to keep typing "y".

Perhaps I am missing something really obvious.

**Comment by TrinathInturi** [comment]
`yes | C:/'Program Files (x86)'/Android/android-sdk/tools/bin/sdkmanager.bat --update`

Add this Command Line Script to your pipeline task it will automatically accept all the license agreements

**Comment by CheeseNPort** [comment]
Thanks yes that sorted it
