### ISSUE TITLE
This repo is not active, Check my fork and Publish

### ISSUE THREAD

**Issue by hey24sheep** [aloisdeniel/vsts-flutter-tasks#50]
I don't think repo is going to be active. The owner is a busy dev. I just checked his work. He is working on other projects. There are a lot of pending/active PR and Issues here since last year.

I needed the fix of 'v' issue ASAP as we prod builds. So, I have created my own fork and publish it to vsts if anyone want to help me keep my repo updated, PR's are welcome. 

Check my fork here [repo](https://github.com/hey24sheep/vsts-flutter-tasks). 

Here is the [extension](https://marketplace.visualstudio.com/items?itemName=Hey24sheep.flutter&ssr=false#overview)

**Comment by aloisdeniel** [comment]
It should be fixed now with latest version (0.2.30).

Let me know if there's still issues on your side.
