### ISSUE TITLE
Something wrong about the download link of the Flutter SDK

### ISSUE THREAD

**Issue by 2377671184** [aloisdeniel/vsts-flutter-tasks#51]
On May 6 2020, Google update the flutter SDK version to 1.17, of which the download link is 
[https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.0-stable.zip](url).
However, the download link generated by the script is 
[https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v.17.0-stable.zip](url).
And this made my build task keep failing, I have overcome the problem by using custom flutter version, but still hope that the problem can be fixed.

**Comment by aloisdeniel** [comment]
It should be fixed now with latest version (0.2.30).

Let me know if there's still issues on your side.
