### ISSUE TITLE
Path does not get set after Install

### ISSUE THREAD

**Issue by flipch** [aloisdeniel/vsts-flutter-tasks#59]
As it stands using your FlutterInstall only allows us to use further Flutter(Commands) from your extension and no bash support.

The problem arises when someone has scripts that make use of flutter binary and it's not available there.

E.g. npm post install script which calls 'flutter pub get'

Is it possible to have the path set?

**Comment by hey24sheep** [comment]
@flipch it already creates a flutter path named "FlutterToolPath". You could use it as "$(FlutterToolPath)/flutter packages get" in your scripts it will work fine.

**Comment by vanlooverenkoen** [comment]
I think it is ok to have an extra variable that contains the flutter path `FlutterToolPath` but it should also be added to the PATH variable itself.
