### ISSUE TITLE
Error build aab

### ISSUE THREAD

**Issue by DevelopGadget** [aloisdeniel/vsts-flutter-tasks#61]
##[error]Error: The process '/Users/runner/hostedtoolcache/Flutter/1.20.2-stable/macos/flutter/bin/flutter' failed with exit code 1

**Comment by 2377671184** [comment]
Yes, I encountered with the same problem. The buildname generated by the script is not an integer, and caused the error.

**Comment by DevelopGadget** [comment]
Perfect!
