### ISSUE TITLE
Error in Flutter Build Task.

### ISSUE THREAD

**Issue by ranjan-roy** [aloisdeniel/vsts-flutter-tasks#68]
I get following error during build.
[log.txt](https://github.com/aloisdeniel/vsts-flutter-tasks/files/5597239/log.txt)

dont have any more details. in log I get following log.
##[error]Error: The process 'C:\hostedtoolcache\windows\Flutter\1.22.4-stable\windows\flutter\bin\flutter.bat' failed with exit code 1

**Comment by Max-Might** [comment]
The actual error in your log file says it is because your build number value is invalid.
It only accepts integers.

```
buildNumber: 20201125.6 was not a valid integer value.
```

You also do not need to pass a build number. If you leave it out the values from the `pubspec.yaml` file will be used for build name and build number.

**Comment by rajatanantharam** [comment]
Add name: $(Date:yyyyMMdd)$(Rev:r) on top of your build yaml. That'll fix it. This is an open issue on flutter.

**Comment by ranjan-roy** [comment]
> Add name: $(Date:yyyyMMdd)$(Rev:r) on top of your build yaml. That'll fix it. This is an open issue on flutter.

I Get following error 
Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.

  ╷

1 │ name: $(Date:yyyyMMdd)$(Rev:r)

  │       ^^^^^^^^^^^^^^^^^^^^^^^^

  ╵

**Comment by rajatanantharam** [comment]
> > Add name: $(Date:yyyyMMdd)$(Rev:r) on top of your build yaml. That'll fix it. This is an open issue on flutter.
> 
> I Get following error
> Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
> 
> ╷
> 
> 1 │ name: $(Date:yyyyMMdd)$(Rev:r)
> 
> │ ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ╵

@ranjan-roy : Add it at the top of the azure-pipelines.yaml. The pubspec is the specification for your flutter module.

**Comment by ranjan-roy** [comment]
> > > Add name: $(Date:yyyyMMdd)$(Rev:r) on top of your build yaml. That'll fix it. This is an open issue on flutter.
> > 
> > 
> > I Get following error
> > Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
> > ╷
> > 1 │ name: $(Date:yyyyMMdd)$(Rev:r)
> > │ ^^^^^^^^^^^^^^^^^^^^^^^^
> > ╵
> 
> @ranjan-roy : Add it at the top of the azure-pipelines.yaml. The pubspec is the specification for your flutter module.

@rajatanantharam This helped.
also got a referance [here](https://stackoverflow.com/questions/63391384/strange-build-error-in-azure-devops-while-using-flutter)
