### ISSUE TITLE
Missing packages pub publish command

### ISSUE THREAD

**Issue by BenBtg** [aloisdeniel/vsts-flutter-tasks#8]
This plugin is great but is missing the ability to publish packages using 
"flutter packages pub publish"
Dry run option would also be useful to test release before hand.

**Comment by aloisdeniel** [comment]
Hi Ben,

IMO, a better approach would be a dedicated dart pub extension that would allow tu customize its location to point to the flutter integrated one. But I have to check if the integrated pub is custimized to a point which makes it **really** specific to Flutter.

But as a workaround you use the flutter install step first, and then point to the flutter executable from the tools folder of the Azure Devops agent. :)

**Comment by rfogar2** [comment]
Hi @aloisdeniel . Can you provide more information in the README about how to utilize the flutter executable for custom flutter scripts?

Great work btw, thank you.

**Comment by aloisdeniel** [comment]
It is now in the readme!

> > Can I run a custom Flutter command ?
> 
> Yes, right after the `Flutter Install` task, a `FlutterToolPath` environment variable points to the `bin` of the Flutter SDK directory. You just have to use `$(FlutterToolPath)` in your following tasks.
